package main

import (
	"github.com/slicebox-api/mcp-server/config"
	"github.com/slicebox-api/mcp-server/models"
	tools_anonymization "github.com/slicebox-api/mcp-server/tools/anonymization"
	tools_boxes "github.com/slicebox-api/mcp-server/tools/boxes"
	tools_meta_data "github.com/slicebox-api/mcp-server/tools/meta_data"
	tools_transactions "github.com/slicebox-api/mcp-server/tools/transactions"
	tools_users "github.com/slicebox-api/mcp-server/tools/users"
	tools_forwarding "github.com/slicebox-api/mcp-server/tools/forwarding"
	tools_series_types "github.com/slicebox-api/mcp-server/tools/series_types"
	tools_general "github.com/slicebox-api/mcp-server/tools/general"
	tools_filtering "github.com/slicebox-api/mcp-server/tools/filtering"
	tools_images "github.com/slicebox-api/mcp-server/tools/images"
	tools_scps "github.com/slicebox-api/mcp-server/tools/scps"
	tools_scus "github.com/slicebox-api/mcp-server/tools/scus"
	tools_logs "github.com/slicebox-api/mcp-server/tools/logs"
	tools_directories "github.com/slicebox-api/mcp-server/tools/directories"
	tools_import "github.com/slicebox-api/mcp-server/tools/import"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_anonymization.CreatePost_anonymization_anonymizeTool(cfg),
		tools_boxes.CreateDelete_boxes_idTool(cfg),
		tools_meta_data.CreateGet_metadata_series_id_seriestagsTool(cfg),
		tools_meta_data.CreatePost_metadata_series_id_seriestagsTool(cfg),
		tools_meta_data.CreateDelete_metadata_series_seriesid_seriestypes_seriestypeidTool(cfg),
		tools_meta_data.CreatePut_metadata_series_seriesid_seriestypes_seriestypeidTool(cfg),
		tools_anonymization.CreatePost_anonymization_keys_queryTool(cfg),
		tools_transactions.CreateGet_transactions_token_statusTool(cfg),
		tools_transactions.CreatePut_transactions_token_statusTool(cfg),
		tools_users.CreatePost_users_loginTool(cfg),
		tools_forwarding.CreateDelete_forwarding_rule_idTool(cfg),
		tools_meta_data.CreatePost_metadata_series_queryTool(cfg),
		tools_series_types.CreateDelete_seriestypes_rules_idTool(cfg),
		tools_meta_data.CreateGet_metadata_studies_id_imagesTool(cfg),
		tools_general.CreateGet_destinationsTool(cfg),
		tools_meta_data.CreateDelete_metadata_series_seriesid_seriestags_seriestagidTool(cfg),
		tools_series_types.CreateDelete_seriestypes_idTool(cfg),
		tools_series_types.CreatePut_seriestypes_idTool(cfg),
		tools_meta_data.CreateGet_metadata_seriestagsTool(cfg),
		tools_meta_data.CreatePost_seriestypes_series_queryTool(cfg),
		tools_general.CreatePost_system_stopTool(cfg),
		tools_boxes.CreatePost_boxes_connectTool(cfg),
		tools_anonymization.CreateGet_anonymization_keys_id_keyvaluesTool(cfg),
		tools_filtering.CreateGet_filtering_associationsTool(cfg),
		tools_filtering.CreatePost_filtering_associationsTool(cfg),
		tools_images.CreatePost_images_deleteTool(cfg),
		tools_meta_data.CreateGet_metadata_imagesTool(cfg),
		tools_images.CreateGet_images_id_attributesTool(cfg),
		tools_meta_data.CreateGet_metadata_patients_id_imagesTool(cfg),
		tools_images.CreatePost_images_jpegTool(cfg),
		tools_anonymization.CreateDelete_anonymization_keys_idTool(cfg),
		tools_anonymization.CreateGet_anonymization_keys_idTool(cfg),
		tools_boxes.CreateGet_boxes_outgoingTool(cfg),
		tools_series_types.CreateGet_seriestypes_rules_id_attributesTool(cfg),
		tools_series_types.CreatePost_seriestypes_rules_id_attributesTool(cfg),
		tools_transactions.CreateGet_transactions_token_outgoingTool(cfg),
		tools_scps.CreateDelete_scps_idTool(cfg),
		tools_scus.CreateDelete_scus_idTool(cfg),
		tools_transactions.CreatePost_transactions_token_outgoing_failedTool(cfg),
		tools_images.CreateGet_images_id_imageinformationTool(cfg),
		tools_boxes.CreateDelete_boxes_incoming_idTool(cfg),
		tools_meta_data.CreateDelete_metadata_series_id_seriestypesTool(cfg),
		tools_meta_data.CreateGet_metadata_series_id_seriestypesTool(cfg),
		tools_transactions.CreateGet_transactions_token_outgoing_pollTool(cfg),
		tools_logs.CreateGet_logTool(cfg),
		tools_logs.CreateDelete_logTool(cfg),
		tools_meta_data.CreatePost_metadata_studies_queryTool(cfg),
		tools_images.CreateGet_images_id_pngTool(cfg),
		tools_anonymization.CreateGet_anonymization_keysTool(cfg),
		tools_directories.CreateDelete_directorywatches_idTool(cfg),
		tools_anonymization.CreatePost_images_id_anonymizedTool(cfg),
		tools_anonymization.CreateGet_anonymization_optionsTool(cfg),
		tools_meta_data.CreatePost_metadata_patients_queryTool(cfg),
		tools_meta_data.CreateGet_metadata_series_id_sourceTool(cfg),
		tools_boxes.CreateGet_boxes_incomingTool(cfg),
		tools_directories.CreateGet_directorywatchesTool(cfg),
		tools_directories.CreatePost_directorywatchesTool(cfg),
		tools_users.CreateGet_usersTool(cfg),
		tools_users.CreatePost_usersTool(cfg),
		tools_images.CreateDelete_images_idTool(cfg),
		tools_images.CreateGet_images_idTool(cfg),
		tools_series_types.CreateGet_seriestypesTool(cfg),
		tools_series_types.CreatePost_seriestypesTool(cfg),
		tools_users.CreateDelete_users_idTool(cfg),
		tools_boxes.CreatePost_boxes_id_sendTool(cfg),
		tools_meta_data.CreateGet_metadata_series_idTool(cfg),
		tools_meta_data.CreateGet_metadata_flatseriesTool(cfg),
		tools_anonymization.CreateGet_anonymization_keys_export_csvTool(cfg),
		tools_filtering.CreateDelete_filtering_associations_idTool(cfg),
		tools_meta_data.CreatePost_metadata_images_queryTool(cfg),
		tools_meta_data.CreateGet_metadata_patientsTool(cfg),
		tools_meta_data.CreateGet_metadata_flatseries_idTool(cfg),
		tools_import.CreateGet_import_sessionsTool(cfg),
		tools_import.CreatePost_import_sessionsTool(cfg),
		tools_meta_data.CreateGet_metadata_studiesTool(cfg),
		tools_meta_data.CreateGet_metadata_seriesTool(cfg),
		tools_meta_data.CreateGet_metadata_patients_idTool(cfg),
		tools_scus.CreateGet_scusTool(cfg),
		tools_scus.CreatePost_scusTool(cfg),
		tools_import.CreateGet_import_sessions_id_imagesTool(cfg),
		tools_boxes.CreateDelete_boxes_outgoing_idTool(cfg),
		tools_series_types.CreateGet_seriestypes_rules_updatestatusTool(cfg),
		tools_meta_data.CreateGet_metadata_images_idTool(cfg),
		tools_scus.CreatePost_scus_id_sendTool(cfg),
		tools_meta_data.CreateGet_metadata_studies_idTool(cfg),
		tools_import.CreateDelete_import_sessions_idTool(cfg),
		tools_import.CreateGet_import_sessions_idTool(cfg),
		tools_filtering.CreateGet_filtering_filtersTool(cfg),
		tools_filtering.CreatePost_filtering_filtersTool(cfg),
		tools_boxes.CreateGet_boxes_incoming_id_imagesTool(cfg),
		tools_anonymization.CreatePut_images_id_anonymizeTool(cfg),
		tools_users.CreatePost_users_logoutTool(cfg),
		tools_forwarding.CreateGet_forwarding_rulesTool(cfg),
		tools_forwarding.CreatePost_forwarding_rulesTool(cfg),
		tools_scps.CreateGet_scpsTool(cfg),
		tools_scps.CreatePost_scpsTool(cfg),
		tools_logs.CreateDelete_log_idTool(cfg),
		tools_transactions.CreatePost_transactions_token_outgoing_doneTool(cfg),
		tools_general.CreateGet_sourcesTool(cfg),
		tools_boxes.CreatePost_boxes_createconnectionTool(cfg),
		tools_users.CreateGet_users_currentTool(cfg),
		tools_images.CreateGet_images_exportTool(cfg),
		tools_images.CreatePost_images_exportTool(cfg),
		tools_general.CreateGet_system_healthTool(cfg),
		tools_series_types.CreateDelete_seriestypes_rules_ruleid_attributes_attributeidTool(cfg),
		tools_boxes.CreateGet_boxes_outgoing_id_imagesTool(cfg),
		tools_images.CreatePut_images_id_modifyTool(cfg),
		tools_filtering.CreateDelete_filtering_filters_idTool(cfg),
		tools_series_types.CreateGet_seriestypes_rulesTool(cfg),
		tools_series_types.CreatePost_seriestypes_rulesTool(cfg),
		tools_filtering.CreateGet_filtering_filters_id_tagpathsTool(cfg),
		tools_filtering.CreatePost_filtering_filters_id_tagpathsTool(cfg),
		tools_filtering.CreateDelete_filtering_filters_id_tagpaths_tagpathidTool(cfg),
		tools_meta_data.CreatePost_metadata_flatseries_queryTool(cfg),
		tools_boxes.CreateGet_boxesTool(cfg),
	}
}
